@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #EAF6FF
  BorderColor #333
}

actor Tutor as T

rectangle "ClassConnect — Homework Management" {
  usecase "Add Homework" as UC_Add
  usecase "Delete Homework" as UC_Del
  usecase "Mark Homework as Done" as UC_Done
  usecase "Mark Homework as Undone" as UC_Undone
  usecase "View Homework List" as UC_View


  usecase "Select Student" as UC_SelectStudent
  usecase "Select Homework Item" as UC_SelectItem
  usecase "Enter Description" as UC_Desc
  usecase "Set Deadline" as UC_Deadline
}

T -- UC_Add
T -- UC_Del
T -- UC_Done
T -- UC_Undone
T -- UC_View


UC_Add ..> UC_SelectStudent : <<include>>
UC_Add ..> UC_Desc          : <<include>>
UC_Add ..> UC_Deadline      : <<include>>

UC_Del ..> UC_SelectStudent : <<include>>
UC_Del ..> UC_SelectItem    : <<include>>

UC_Done ..> UC_SelectStudent : <<include>>
UC_Done ..> UC_SelectItem    : <<include>>

UC_Undone ..> UC_SelectStudent : <<include>>
UC_Undone ..> UC_SelectItem    : <<include>>

UC_View ..> UC_SelectStudent : <<include>>
@enduml
